theme = "catppuccin_macchiato"

[editor]
auto-pairs = false
bufferline = "always"
color-modes = true
mouse = false
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # deselect all and keep primary cursor same as ";,"
C-h = "goto_next_buffer"
C-l = "goto_previous_buffer"

[keys.normal.space]
B = ":sh gh browse %{buffer_name}:%{cursor_line}"
w = ":buffer-close"

[keys.normal.C-w]
tab = "rotate_view"
