theme = "catppuccin_macchiato"

[editor]
auto-pairs = false
bufferline = "always"
color-modes = true
completion-timeout = 5
cursorline = true
end-of-line-diagnostics = "hint"
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
mouse = false
rainbow-brackets = true
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.statusline]
right= ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.soft-wrap]
enable = true

[editor.word-completion]
enable = true
trigger-length = 2

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"] # deselect all and keep primary cursor same as ";,"
x = ["extend_to_line_bounds", "select_mode"]
X = ["extend_to_line_bounds", "select_mode"]
C-b = ':sh git blame "-L $(( %{cursor_line} - 5 < 1 ? 1 : %{cursor_line} - 5 )),$(( %{cursor_line} + 5 ))" %{buffer_name}'
C-h = "goto_previous_buffer"
C-l = "goto_next_buffer"
C-r = ":reload-all"
C-t = ':sh name=$(basename %{buffer_name} | cut -c1-10) && tmux rename-window "hx: ${name}"' # manually set until helix supports hooks or plugins

# Vim motions
0 = "goto_line_start"
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
G = "goto_last_line"
H = "goto_window_top"
L = "goto_window_bottom"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.normal.space]
B = ":echo %sh{gh browse %{buffer_name}:%{cursor_line} || gh browse --no-browser %{buffer_name}:%{cursor_line}}" # print URL in case we are in en env without a browser
w = ":buffer-close"

[keys.normal.C-w]
tab = "rotate_view"

[keys.select]
x = ["extend_line"]
X = ["extend_line_above"]

# Vim motions
0 = "extend_to_line_start"
"^" = "extend_to_first_nonwhitespace"
"$" = "extend_to_line_end"
G = "extend_to_last_line"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select.g]
q = ":reflow"
